name: design_system
description: A simple design system to provide components, fonts, atoms for the system.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: 5.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.0.20
  mocktail: ^0.2.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png

