name: api_client
description: Package for managing api requests
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^3.0.6
  dio: 5.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.5.3
  mocktail: ^0.2.0

