name: utils
description: Provide basic utils classes, like number utils, UI utils, string utils, array utils, etc ...
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 2.0.20
  mockito: ^5.4.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
